import * as Type$dProxy from "../Type.Proxy/index.js";
import {unsafeGetFirstField} from "./foreign.js";
const singletonRecordFieldsNil = () => ({singletonRecordFields: v => v1 => {}});
const singletonRecordFieldsCons = () => ({singletonRecordFields: v => v1 => {}});
const singletonRecordFieldsCons1 = () => () => dictIsSymbol => ({singletonRecordFields: v => v1 => Type$dProxy.Proxy});
const singletonRecord = () => ({key: v => {}, value: v => {}});
const value = dict => dict.value;
const singletonRecordFields = dict => dict.singletonRecordFields;
const singletonRecord1 = () => dictSingletonRecordFields => ({key: dictSingletonRecordFields.singletonRecordFields(Type$dProxy.Proxy), value: unsafeGetFirstField});
const key = dict => dict.key;
export {key, singletonRecord, singletonRecord1, singletonRecordFields, singletonRecordFieldsCons, singletonRecordFieldsCons1, singletonRecordFieldsNil, value};
export * from "./foreign.js";
